In [5]:
from caffe2.python import workspace, model_helper
import numpy as np

In [6]:
# Create random tensor of three dimensions
x = np.random.rand(4, 3, 2)
print(x)
print(x.shape)

workspace.FeedBlob("my_x", x)

x2 = workspace.FetchBlob("my_x")
print(x2)

[[[0.65798152 0.29509617]
  [0.83669679 0.53581634]
  [0.42895872 0.91485355]]

 [[0.63881674 0.24590494]
  [0.95909306 0.54743433]
  [0.68625738 0.33151325]]

 [[0.02689118 0.64815923]
  [0.56353949 0.25357652]
  [0.57252087 0.29994826]]

 [[0.35121854 0.52887886]
  [0.11951092 0.03861707]
  [0.28471758 0.33432999]]]
(4, 3, 2)
[[[0.65798152 0.29509617]
  [0.83669679 0.53581634]
  [0.42895872 0.91485355]]

 [[0.63881674 0.24590494]
  [0.95909306 0.54743433]
  [0.68625738 0.33151325]]

 [[0.02689118 0.64815923]
  [0.56353949 0.25357652]
  [0.57252087 0.29994826]]

 [[0.35121854 0.52887886]
  [0.11951092 0.03861707]
  [0.28471758 0.33432999]]]
